### ISSUE TITLE
Batch processing broken on v8.1

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [anothermartz/Easy-Wav2Lip#13]
Error logs:

Traceback (most recent call last):
  File "/content/Easy-Wav2Lip/run.py", line 80, in <module>
    in_width, in_height, in_fps, in_length = get_video_details(video_file)
  File "/content/Easy-Wav2Lip/easy_functions.py", line 19, in get_video_details
    info = json.loads(result.stdout)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by anothermartz** [comment]
I can't replicate this issue, do you only get this while batch processing?
What filetype are you using?

Length, resolutiion, fps of the video? If you can share your inputs that'll be great!
