### ISSUE TITLE
Error running Easy_Wav2Lip_v8.3.ipynb

### ISSUE THREAD

**Issue by dijkstra-mose** [anothermartz/Easy-Wav2Lip#59]
imports loaded!     
Traceback (most recent call last):
  File "/home/work/anaconda3/envs/dvh/lib/python3.10/configparser.py", line 790, in get
    value = d[option]
  File "/home/work/anaconda3/envs/dvh/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/work/anaconda3/envs/dvh/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'preview_window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/work/workspace/dvh/Easy-Wav2Lip/inference.py", line 256, in <module>
    preview_window = config.get('OPTIONS', 'preview_window')
  File "/home/work/anaconda3/envs/dvh/lib/python3.10/configparser.py", line 793, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'preview_window' in section: 'OPTIONS'
Processing failed! :( see line above 👆
Consider searching the issues tab on the github:
https://github.com/anothermartz/Easy-Wav2Lip/issues

**Comment by ripa001** [comment]
I fixed it by adding "preview_window" to False into the options dictionary:
```
options = {
   ...
    "preview_window": False
}
```
I'm not sure actually if it is the right solution, but I incurred the same error running it out of google colab
