### ISSUE TITLE
No module named 'dlib'

### ISSUE THREAD

**Issue by zachysaur** [anothermartz/Easy-Wav2Lip#66]
opening GUI
Saving config
starting Easy-Wav2Lip...
Traceback (most recent call last):
  File "F:\Wav2Lip-8.3\Easy-Wav2Lip-8.3_release\run.py", line 5, in <module>
    from easy_functions import (format_time,
  File "F:\Wav2Lip-8.3\Easy-Wav2Lip-8.3_release\easy_functions.py", line 5, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'
opening GUI

**Comment by caomeng528** [comment]
我的是conda虚拟环境使用 conda install -c conda-forge dlib
