### ISSUE TITLE
RuntimeError looking for CUDA when running on M3 Mac

### ISSUE THREAD

**Issue by oskapt** [anothermartz/Easy-Wav2Lip#71]
`install.py` throws the following error when running on Apple Silicon:

```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. 
If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') 
to map your storages to the CPU.
```

The solution was to change line 83 of `easy_functions.py` to explicitly reference the device value stored in the `device` variable:

```
--- a/easy_functions.py
+++ b/easy_functions.py
@@ -80,7 +80,7 @@ def format_time(seconds):

 def _load(checkpoint_path):
     if device != "cpu":
-        checkpoint = torch.load(checkpoint_path)
+        checkpoint = torch.load(checkpoint_path, map_location=torch.device(device))
     else:
         checkpoint = torch.load(
             checkpoint_path, map_location=lambda storage, loc: storage
```

I'm not submitting a PR bc I can't be bothered to fork this repo when I don't even know if it will work past the install. Leaving this here for anyone else who's trying to run this on a Mac.

**Comment by SAKURA-LBY** [comment]
I would like to ask, I encountered this error when I run `python install.py`:
```sh
 Traceback (most recent call last):
  File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip/install.py", line 66, in <module>
    model = load_model(os.path.join(working_directory, "checkpoints", "Wav2Lip.pth"))
  File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip/easy_functions.py", line 102, in load_model
    checkpoint = _load(path)
  File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip/easy_functions.py", line 83, in _load
    checkpoint = torch.load(checkpoint_path, map_location=torch.device(device))
  File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip-venv/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip-venv/lib/python3.10/site-packages/torch/serialization.py", line 1264, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 1339103 more bytes. The file might be corrupted.


```

**Comment by SAKURA-LBY** [comment]
> I would like to ask, I encountered this error when I run`python install.py`：
> 
> ```shell
>  Traceback (most recent call last):
>   File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip/install.py", line 66, in <module>
>     model = load_model(os.path.join(working_directory, "checkpoints", "Wav2Lip.pth"))
>   File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip/easy_functions.py", line 102, in load_model
>     checkpoint = _load(path)
>   File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip/easy_functions.py", line 83, in _load
>     checkpoint = torch.load(checkpoint_path, map_location=torch.device(device))
>   File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip-venv/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/Users/luadasd/develop/easywav2lip/Easy-Wav2Lip-venv/lib/python3.10/site-packages/torch/serialization.py", line 1264, in _legacy_load
>     typed_storage._untyped_storage._set_from_file(
> RuntimeError: unexpected EOF, expected 1339103 more bytes. The file might be corrupted.
> ```

Could you tell me if you have encountered this problem?
My computer is a Mac M1
