### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by nitinmukesh** [anothermartz/Easy-Wav2Lip#75]
Torch is installed, still.

```
(venv) C:\sd\Easy-Wav2Lip-WebUI>python app.py
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.29.69:80
Press CTRL+C to quit
127.0.0.1 - - [24/Jun/2024 15:34:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Jun/2024 15:34:14] "GET /favicon.ico HTTP/1.1" 404 -
Traceback (most recent call last):
  File "C:\sd\Easy-Wav2Lip-WebUI\run.py", line 4, in <module>
    from easy_functions import (format_time,
  File "C:\sd\Easy-Wav2Lip-WebUI\easy_functions.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
[2024-06-24 15:46:25,477] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\sd\Easy-Wav2Lip-WebUI\app.py", line 40, in upload_file
    return render_template('result.html', output_file=output_file)
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\sd\Easy-Wav2Lip-WebUI\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: result.html
127.0.0.1 - - [24/Jun/2024 15:46:25] "POST / HTTP/1.1" 500 -

```

```
(venv) C:\sd\Easy-Wav2Lip-WebUI>pip list
Package                 Version
----------------------- ---------------
absl-py                 2.1.0
addict                  2.4.0
asttokens               2.4.1
audioread               3.0.1
backcall                0.2.0
basicsr                 1.4.2
batch-face              1.4.0
beautifulsoup4          4.12.3
blinker                 1.8.2
certifi                 2024.6.2
cffi                    1.16.0
charset-normalizer      3.3.2
click                   8.1.7
colorama                0.4.6
configparser            7.0.0
contourpy               1.2.1
cycler                  0.12.1
decorator               4.4.2
dlib                    19.22.99
exceptiongroup          1.2.1
executing               2.0.1
facexlib                0.3.0
filelock                3.15.4
filterpy                1.4.5
Flask                   3.0.3
fonttools               4.53.0
fsspec                  2024.6.0
future                  1.0.0
gdown                   4.7.1
gfpgan                  1.3.8
grpcio                  1.64.1
idna                    3.7
imageio                 2.34.2
imageio-ffmpeg          0.4.9
importlib-metadata      6.8.0
ipython                 8.16.1
itsdangerous            2.2.0
jedi                    0.19.1
Jinja2                  3.1.4
joblib                  1.4.2
kiwisolver              1.4.5
lazy_loader             0.4
librosa                 0.10.1
llvmlite                0.43.0
lmdb                    1.4.1
Markdown                3.6
MarkupSafe              2.1.5
matplotlib              3.9.0
matplotlib-inline       0.1.7
moviepy                 1.0.3
mpmath                  1.3.0
msgpack                 1.0.8
networkx                3.3
numba                   0.60.0
numpy                   1.26.1
opencv-python           4.8.1.78
packaging               24.1
parso                   0.8.4
pickleshare             0.7.5
pillow                  10.3.0
pip                     22.2.1
platformdirs            4.2.2
pooch                   1.8.2
proglog                 0.1.10
prompt_toolkit          3.0.47
protobuf                4.25.3
pure-eval               0.2.2
pycparser               2.22
Pygments                2.18.0
pyparsing               3.1.2
PySocks                 1.7.1
python-dateutil         2.9.0.post0
PyYAML                  6.0.1
requests                2.32.3
scikit-image            0.24.0
scikit-learn            1.5.0
scipy                   1.11.3
setuptools              63.2.0
six                     1.16.0
soundfile               0.12.1
soupsieve               2.5
soxr                    0.3.7
stack-data              0.6.3
sympy                   1.12.1
tb-nightly              2.18.0a20240616
tensorboard-data-server 0.7.2
threadpoolctl           3.5.0
tifffile                2024.6.18
tomli                   2.0.1
torch                   2.1.0+cu121
torchaudio              2.1.0+cu121
torchvision             0.16.0+cu121
tqdm                    4.66.4
traitlets               5.14.3
typing_extensions       4.12.2
urllib3                 2.2.2
wcwidth                 0.2.13
Werkzeug                3.0.3
yapf                    0.40.2
zipp                    3.19.2
```

**Comment by VivekGangurde94** [comment]
Did you find the solution for this as i m facing the same problem ?
