### ISSUE TITLE
这是啥原因啊

### ISSUE THREAD

**Issue by fxai666** [anothermartz/Easy-Wav2Lip#83]
Traceback (most recent call last):
  File "K:\Wav2Lip\Easy-Wav2Lip\inference.py", line 780, in <module>
    do_load(args.checkpoint_path)
  File "K:\Wav2Lip\Easy-Wav2Lip\inference.py", line 265, in do_load
    detector = RetinaFace(
  File "K:\Wav2Lip\Easy-Wav2Lip-venv\lib\site-packages\batch_face\face_detection\detector.py", line 48, in __init__
    self.model = load_net(model_path, self.device, network)
  File "K:\Wav2Lip\Easy-Wav2Lip-venv\lib\site-packages\batch_face\face_detection\alignment.py", line 483, in load_net
    net = load_model(net, model_path, True, network=network)
  File "K:\Wav2Lip\Easy-Wav2Lip-venv\lib\site-packages\batch_face\face_detection\alignment.py", line 457, in load_model
    pretrained_dict = torch.load(
  File "K:\Wav2Lip\Easy-Wav2Lip-venv\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "K:\Wav2Lip\Easy-Wav2Lip-venv\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "K:\Wav2Lip\Easy-Wav2Lip-venv\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/mobilenet.pth'
Processing failed! :( see line above 👆
Consider searching the issues tab on the github:
https://github.com/anothermartz/Easy-Wav2Lip/issues

**Comment by fxai666** [comment]
已好了

**Comment by lhbtata** [comment]
@15810208908 您好，我遇到了相同的问题，请问您是怎么解决的
