### ISSUE TITLE
Collab error re:"codec none"

### ISSUE THREAD

**Issue by Erreinion** [anothermartz/Easy-Wav2Lip#84]
```
Traceback (most recent call last):
  File "/content/Easy-Wav2Lip/run.py", line 336, in <module>
    ffmpeg_extract_subclip(
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/ffmpeg_tools.py", line 41, in ffmpeg_extract_subclip
    subprocess_call(cmd)
  File "/usr/local/lib/python3.10/dist-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/Easy-Wav2Lip/temp/01000Phil-C0070-trimmed-720p_2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2024-08-30T11:39:24.000000Z
    encoder         : Blackmagic Design DaVinci Resolve
  Duration: 00:00:53.72, start: 0.000000, bitrate: 2468 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 2208 kb/s, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2024-08-30T11:39:24.000000Z
      handler_name    : VideoHandler
      timecode        : 01:00:00:00
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 255 kb/s (default)
    Metadata:
      creation_time   : 2024-08-30T11:39:24.000000Z
      handler_name    : SoundHandler
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74) (default)
    Metadata:
      creation_time   : 2024-08-30T11:39:24.000000Z
      handler_name    : TimeCodeHandler
      timecode        : 01:00:00:00
[mp4 @ 0x64d0c00] You requested a copy of the original timecode track so timecode metadata are now ignored
[mp4 @ 0x64d0c00] Could not find tag for codec none in stream #2, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
    Last message repeated 1 times
```
Need error handling for  Stream #0:2(eng): Data: none

I used Davinci Resolve to edit a video for use here. Tried to create data burn in, but got the same error

**Comment by Erreinion** [comment]
The problem appears to have gone away all by itself. Same files. Same settings. Works fine...

**Comment by Erreinion** [comment]
The problem appears to have gone away all by itself. Same files. Same settings. Works fine...
