### ISSUE TITLE
problem with Wav2Lip

### ISSUE THREAD

**Issue by lukaetf** [anothermartz/Easy-Wav2Lip#90]
Traceback (most recent call last):
  File "/content/Easy-Wav2Lip/inference.py", line 781, in <module>
    main()
  File "/content/Easy-Wav2Lip/inference.py", line 757, in main
    cv2.destroyAllWindows()
cv2.error: OpenCV(4.10.0) /io/opencv/modules/highgui/src/window.cpp:1295: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

Processing failed! :( see line above 👆
Consider searching the issues tab on the github:

**Comment by EvtielCore** [comment]
Same

**Comment by deathpriest83** [comment]
I changed to version 8.2 and it's working for me right now

**Comment by salmanahmad78699** [comment]
> I changed to version 8.2 and it's working for me right now

Version of which thing? Provide details.

**Comment by salmanahmad78699** [comment]
Is this a Colab error?

**Comment by deathpriest83** [comment]
Just view the code and where it says v8.3 just change that to version 8.2
