### ISSUE TITLE
The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

### ISSUE THREAD

**Issue by BogdanKorniyko** [anothermartz/Easy-Wav2Lip#95]
When I try to collect the video in step 2 in colab.research.google.com, I get an error

`Processing 2 Омоложение.mp4 using 2 Bulgaria P 2 (1).MP3 for audio
imports loaded!     
Converting audio to .wav
analysing audio...
1364 frames to process
detecting face in every frame: 100%|███████████████████████████| 1364/1364 [00:11<00:00, 119.78it/s]
Starting...
Processing Wav2Lip: 100%|███████████████████████████████████████| 1364/1364 [00:33<00:00, 40.97it/s]
Traceback (most recent call last):
  File "/content/Easy-Wav2Lip/inference.py", line 781, in <module>
    main()
  File "/content/Easy-Wav2Lip/inference.py", line 757, in main
    cv2.destroyAllWindows()
cv2.error: OpenCV(4.10.0) /io/opencv/modules/highgui/src/window.cpp:1295: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

Processing failed! :( see line above 👆
Consider searching the issues tab on the github:
https://github.com/anothermartz/Easy-Wav2Lip/issues`

**Comment by kenist0n** [comment]
you need to downgrade cv2 to a version that has destroyAllWindows(), then it should work again

!pip uninstall opencv-python opencv-contrib-python opencv-python-headless opencv-contrib-python-headless -y
!pip install opencv-python==4.5.5.64
