### ISSUE TITLE
No such file or directory: 'checkpoints/predictor.pkl'

### ISSUE THREAD

**Issue by WachasWps** [anothermartz/Easy-Wav2Lip#97]
Traceback (most recent call last):
  File "<ipython-input-10-11e073910a27>", line 107, in ask_avatar
    perform_lip_sync(VIDEO_PATH, AUDIO_PATH, lip_synced_video)
  File "<ipython-input-10-11e073910a27>", line 77, in perform_lip_sync
    raise e
  File "<ipython-input-10-11e073910a27>", line 73, in perform_lip_sync
    raise RuntimeError(f"Easy-Wav2Lip execution failed: {result.stderr}")
RuntimeError: Easy-Wav2Lip execution failed: Traceback (most recent call last):
  File "/content/Easy-Wav2Lip/inference.py", line 239, in <module>
    with open(os.path.join("checkpoints", "predictor.pkl"), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/predictor.pkl'

INFO:werkzeug:127.0.0.1 - - [25/Dec/2024 23:57:02] "POST /ask HTTP/1.1" 500 -
Error: Traceback (most recent call last):
  File "/content/Easy-Wav2Lip/inference.py", line 239, in <module>
    with open(os.path.join("checkpoints", "predictor.pkl"), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/predictor.pkl'

Error in lip-syncing process: Easy-Wav2Lip execution failed: Traceback (most recent call last):
  File "/content/Easy-Wav2Lip/inference.py", line 239, in <module>
    with open(os.path.join("checkpoints", "predictor.pkl"), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/predictor.pkl'

**Comment by qwhynot** [comment]
same error

**Comment by qwhynot** [comment]
to solve the problem you need to run install.py
